global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'platform-fastapi'
    static_configs:
      - targets: ['platform-fastapi:8000']
    metrics_path: /metrics

  - job_name: 'erpnext'
    static_configs:
      - targets: ['erpnext-frontend:8000']
    metrics_path: /api/method/frappe.utils.redis_monitor.get_redis_status
